# Generated by Django 4.1.8 on 2023-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platopedidos',
            name='observacion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
