# Generated by Django 4.1.8 on 2023-05-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mesas', '0001_initial'),
        ('pedidos', '0002_alter_pedidos_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='mesa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mesas.mesa'),
        ),
    ]
