# Generated by Django 4.1.8 on 2023-06-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
        ('pedidos', '0002_alter_platopedidos_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platopedidos',
            name='plato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='platos.platos'),
        ),
    ]
