# Generated by Django 4.1.8 on 2023-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_platopedidos_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='precio_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
