# Generated by Django 4.1.8 on 2023-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='precio_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
