# Generated by Django 4.1.8 on 2023-05-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero_mesa',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
